server:
  port: 8080

spring:
  application:
    name: glf-accounts
  profiles:
    active: dev

  config:
    import:
      - "configserver:http://localhost:8071/"
      - "classpath:buildInfo.yml"
      - "classpath:buildEnvInfo.yml"

springdoc:
  api-docs:
    path: /api-docs

info:
  app:
    name: "glf-accounts"
    description: "Goaleaf accounts application."
    version: "0.0.1-SNAPSHOT"
